config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :lists
  root "lists#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  validates_presence_of :title, :due_date, :description

  def can_destroy?
    !overdue?
  end

  private
  def overdue?
    due_date< Date.today
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
  @list = List.new(list_params)
  if @list.save
    redirect_to lists_url
  else
    render  :action => :new
  end
end

  def show
    @list = List.find(params[:id])
  end

  def  edit
    @list = List.find(params[:id])

  end

  def update
  @list = List.find(params[:id])
  if @list.update_attributes(list_params)
    redirect_to list_path(@list)
  else
    render  :action => :edit
  end
end

  def destroy
    @list = List.find(params[:id])
    if @list.can_destroy?

    @list.destroy
    flash[:alert] = '成功刪除'
    redirect_to lists_url, notice: 'The Due Date is over'

    else
    flash[:alert] = '已經過期無法刪除'
    redirect_to lists_url
    end

  end

  private

  def list_params
    params.require(:list).permit(:title, :due_date, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

   <% if flash.present? %>
     <div class="amendmsg">
       <p style="color: green" align="center"><%= flash[:notice] %></p>
       <p style="color: red" align="center" ><%= flash[:alert] %></p>
     </div>
   <% end %>
   <%= yield %>

  </body>
</html>

app/views/lists/_form.html.erb
<% if @list.errors.present? %>
  <ul>
    <% @list.errors.each do |error, message| %>
      <li> <%= "#{error.capitalize}  #{message}" %></li>
    <% end %>
  </ul>
<% end %>

<div class="form container">
<%= form_for @list do|f| %>
<div class="form-group">
  <%= f.label :title, "Title" %>
  <%= f.text_field :title, class: "form-control" %>
<div class="form-group">
  <%= f.label :date, "Due Date" %>
  <%= f.text_field :due_date, class: "form-control"%>
<div class="form-group">
  <%= f.label :description, "Description" %>
  <%= f.text_area :description, class: "form-control"%>

  <%= f.submit  %>
<% end %>
</div>

app/views/lists/edit.html.erb
<%= render :partial => "form" %>

app/views/lists/index.html.erb
<div class="container">
  <h1>待辦事項</h1>

<table class="table table-striped table-condensed">
  <thead>
    <tr>
      <th>待辦項目</th>
      <th>詳細內容</th>
      <th>內容編輯</th>
      <th>截止日</th>
      <th>刪除項目</th>
    </tr>
  </thead>
  <tbody>
  <% @lists.each do |list| %>
  <tr>
    <td><%= list.title %></td>
    <td><%= link_to 'Show' , list_path(list) %></td>
    <td><%= link_to 'Edit' , edit_list_path(list) %></td>
    <td><%= list.due_date.to_s.slice(0..9) %></td>
    <td><%= link_to 'Destroy' , list_path(list), method: :delete, data:{ confirm: "Are you sure?"} %></td>
  </tr>
  <% end %>
</tbody>
</table>

<%= link_to 'New to do list', new_list_path %>
</div>

app/views/lists/new.html.erb
<%= render :partial => "form" %>

app/views/lists/show.html.erb
<div class="wrapper">

  <h1 class="title"><%= @list.title %></h1>

  <p class="due_date">Due date<%= @list.due_date %></p>
</div>
  <p id="description">
  <%= simple_format(@list.description) %></p>

  <div class="itembox_btn">

      <%= link_to 'Back to index', lists_path, class: 'btn btn-default' %>
  </div>